#!/usr/bin/env python3
"""Fail if a line's tooltip or highlight disagrees with what that line actually says.

Why this exists
---------------
E01 shipped a render where the caption read "these long lines are called rods" while the
tooltip read "This is Frame of Abacus" — the whole anatomy block was one line out of step.
The cause was a hand-numbered lookup table built from a guessed phrase list.

src/data/lineMap.ts is now generated by matching each line's text, but a generated file
can still be regenerated wrongly, so this asserts the invariant directly: if a line
mentions a part, the tooltip attached to it must be about that part.

This checks E01 specifically, because it reads src/data/lineMap.ts — the generated table
that only E01 uses. E02 asserts the same invariant at RENDER time instead, in
src/data/e02Cards.ts (`assertCards`), which is stronger: it cannot be skipped and it does
not need a Python parser for TypeScript.

Usage:
    python3 tools/check_line_sync.py [phrases.json]
Exit code 1 on any mismatch.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# What each app tooltip is ABOUT, as a set of words that must appear in a line that uses it.
TOOLTIP_SUBJECT = {
    0: {"frame", "outside", "holds"},
    1: {"rods", "columns", "lines", "same"},
    2: {"beam", "bar", "middle"},
    3: {"top", "above"},
    4: {"bottom", "below"},
    5: {"upper"},
    6: {"lower", "four"},
    7: {"ones", "right", "start", "column"},
    8: {"one", "five", "clever", "little"},
    9: {"ten", "fifty", "left", "bigger"},
    10: {"hundred", "left", "bigger", "times"},
    11: {"nine", "rod", "zero"},
    12: {"ninety", "rods", "zero"},
    13: {"hundred", "ninety", "rods"},
    14: {"add", "lower", "thumb", "up"},
    15: {"add", "upper", "index", "down"},
    16: {"subtract", "lower", "index", "down"},
    17: {"subtract", "upper", "thumb", "up"},
}

# A line naming a part must be highlighted on that part.
PART_WORDS = {
    "frame": ("frame", "outside"),
    "rods": ("rods", "columns", "lines"),
    "beam": ("beam", "bar"),
    "top": ("top", "above", "upper"),
    "bottom": ("bottom", "below", "lower"),
}


def load_map(name: str) -> dict[int, str]:
    src = (ROOT / "src/data/lineMap.ts").read_text()
    m = re.search(rf"export const {name}[^=]*= \{{(.*?)\}};", src, re.S)
    if not m:
        return {}
    out: dict[int, str] = {}
    for k, v in re.findall(r"(\d+):\s*\"?([A-Za-z0-9]+)\"?", m.group(1)):
        out[int(k)] = v
    return out


def main() -> int:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "src/data/e01.phrases.json"
    phrases = json.loads(src.read_text())
    text = {p["index"]: p["text"].lower() for p in phrases}
    tips = {k: int(v) for k, v in load_map("LINE_TOOLTIP").items()}
    highs = load_map("LINE_HIGHLIGHT")

    problems: list[str] = []

    # A line that names no part legitimately INHERITS the previous line's part —
    # "it holds everything together" is still about the frame. The error to catch is a
    # line that names part X while the tooltip or highlight is about a different part.
    def parts_named(words: set[str]) -> set[str]:
        return {part for part, ws in PART_WORDS.items() if words & set(ws)}

    for idx, tip in sorted(tips.items()):
        if idx not in text:
            problems.append(f"line {idx}: tooltip {tip} but there is no such phrase")
            continue
        words = set(re.findall(r"[a-z]+", text[idx]))
        named = parts_named(words)
        subject = TOOLTIP_SUBJECT.get(tip, set())
        # only complain when the line names a part AND the tooltip shares no word with it
        if named and subject and not (words & subject):
            problems.append(
                f"line {idx}: names {sorted(named)} but tooltip {tip} is about "
                f"{sorted(subject)} -- {text[idx][:52]!r}"
            )

    for idx, part in sorted(highs.items()):
        words = set(re.findall(r"[a-z]+", text.get(idx, "")))
        named = parts_named(words)
        if named and part not in named:
            problems.append(
                f"line {idx}: names {sorted(named)} but is highlighted on {part!r}"
                f" -- {text[idx][:52]!r}"
            )

    if problems:
        print(f"{len(problems)} line-sync problem(s):\n", file=sys.stderr)
        for p in problems:
            print("  " + p, file=sys.stderr)
        return 1

    print(f"line sync OK — {len(tips)} tooltips and {len(highs)} highlights all agree "
          f"with the text of the line they are attached to")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
