#!/usr/bin/env python3
"""Generate src/data/lineMap.ts by matching each spoken line's TEXT.

Never hand-number a phrase-index table. The first version was hand-numbered from a guessed
phrase list, came out shifted by one across the whole anatomy block, and shipped a video
whose tooltip said "This is Frame of Abacus" while the narration said "these long lines are
called rods".

Rules must be SPECIFIC enough not to collide. "one upper bead" matched both
  21  Each rod has one upper bead.          (the anatomy lesson)
  70  One upper bead and two lower beads.   (the your-turn reveal)
so line 70 inherited the anatomy tooltip. Anchor on the words that make a line unique.

Usage:  python3 tools/gen_line_map.py [phrases.json]
Then:   python3 tools/check_line_sync.py
E01 tooling: it writes src/data/lineMap.ts, which only E01 reads. E02 keeps its card
table in src/data/e02Cards.ts and asserts it at render time (`assertCards`).

"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# (substring, tooltip index or None, highlight or None, bead-count mode or None)
# Order matters: the first match wins, so put the more specific phrase first.
RULES: list[tuple[str, int | None, str | None, str | None]] = [
    ("called the frame", 0, "frame", None),
    ("holds everything together", 0, "frame", None),
    ("called rods", 1, "rods", None),
    ("call them columns", 1, "rods", None),
    ("mean the same thing", 1, "rods", None),
    ("middle is the beam", 2, "beam", None),
    ("call it the bar", 2, "beam", None),
    ("beam is very important", None, "beam", None),
    ("splits the abacus", None, "beam", None),
    ("above the beam is the top", 3, "top", None),
    ("below the beam is the bottom", 4, "bottom", None),
    ("look at the top", None, "top", None),
    # anchored on "has", so the your-turn reveal on line 70 does not match
    ("has one upper bead", 5, "top", "upper"),
    ("look at the bottom", None, "bottom", None),
    ("has four lower beads", 6, "bottom", "lower"),
    ("heaven beads and earth beads", None, None, None),
    ("upper and lower are the names", None, None, None),
    ("rod on the far right", 7, None, None),
    ("is the ones column", 7, None, None),
    ("where we always start", 7, None, None),
    ("lower bead is worth one.", 8, "bottom", None),
    ("upper bead is worth five.", 8, "top", None),
    ("little bead, worth five", 8, "top", None),
    ("clever part", 8, None, None),
    # specific before loose: "value becomes ten times bigger" is line 40's summary and
    # must not be swallowed by the tens rule. Fixing this in the GENERATED file instead of
    # here is what made the bug come back after the next regeneration.
    # line 40 generalises the pattern; it is not about one rod, so no rod card. It used
    # to inherit the hundreds tooltip, which contradicted the sentence.
    ("value becomes ten times bigger", None, None, None),
    ("move one rod to the left", 9, None, None),
    ("becomes ten times bigger", 9, None, None),
    ("now worth ten", 9, "bottom", None),
    ("worth fifty", 9, "top", None),
    ("move one more rod left", 10, None, None),
    ("worth one hundred", 10, "bottom", None),
    ("worth five hundred", 10, "top", None),
    ("from zero to nine.", 11, None, None),
    ("zero to ninety-nine", 12, None, None),
    ("nine hundred and ninety-nine", 13, None, None),
    ("push them up with your thumb", 14, "bottom", None),
    ("pull it down with your index", 15, "top", None),
    ("push them down with your index", 16, "bottom", None),
    ("push it back up with your thumb", 17, "top", None),
]


def main() -> int:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "src/data/e01.phrases.json"
    phrases = json.loads(src.read_text())

    tip: dict[int, int] = {}
    hl: dict[int, str] = {}
    cnt: dict[int, str] = {}

    for x in phrases:
        low = x["text"].lower()
        for sub, t, h, c in RULES:
            if sub in low:
                if t is not None:
                    tip[x["index"]] = t
                if h is not None:
                    hl[x["index"]] = h
                if c is not None:
                    cnt[x["index"]] = c
                break

    # a tooltip must not appear on two runs that are far apart — that means a rule collided
    for step in set(tip.values()):
        lines = sorted(k for k, v in tip.items() if v == step)
        if lines and lines[-1] - lines[0] > 8:
            print(
                f"WARNING tooltip {step} spans lines {lines} — a rule is probably too "
                f"loose and is matching an unrelated line",
                file=sys.stderr,
            )

    def fmt(m: dict, quote: bool = False) -> str:
        inner = ", ".join(
            f'{k}: {chr(34) + str(v) + chr(34) if quote else v}' for k, v in sorted(m.items())
        )
        return "{ " + inner + " }"

    out = f'''// GENERATED by tools/gen_line_map.py — do not hand-edit, re-run the generator.
//
// Each entry is derived by matching the spoken line's TEXT, because a hand-numbered table
// shipped a whole section one line out of step. See the generator for the rules and for
// the collision that put the anatomy tooltip on the your-turn reveal.

/** phrase index -> index into the app's freeModeHighlightSteps */
export const LINE_TOOLTIP: Record<number, number> = {fmt(tip)};

/** phrase index -> which part of the abacus this line is about */
export const LINE_HIGHLIGHT: Record<number, "frame" | "rods" | "beam" | "top" | "bottom"> = {fmt(hl, True)};

/** phrase index -> number the beads while the narration counts them */
export const LINE_COUNT: Record<number, "upper" | "lower"> = {fmt(cnt, True)};
'''
    (ROOT / "src/data/lineMap.ts").write_text(out)
    print(f"wrote src/data/lineMap.ts — {len(tip)} tooltips, {len(hl)} highlights, {len(cnt)} counts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
