// GENERATED by tools/gen_line_map.py — do not hand-edit, re-run the generator.
//
// Each entry is derived by matching the spoken line's TEXT, because a hand-numbered table
// shipped a whole section one line out of step. See the generator for the rules and for
// the collision that put the anatomy tooltip on the your-turn reveal.

/** phrase index -> index into the app's freeModeHighlightSteps */
export const LINE_TOOLTIP: Record<number, number> = { 9: 0, 10: 0, 11: 1, 12: 1, 13: 1, 14: 2, 15: 2, 18: 3, 19: 4, 21: 5, 23: 6, 26: 7, 27: 7, 28: 7, 29: 8, 30: 8, 31: 8, 32: 8, 33: 9, 34: 9, 35: 9, 36: 9, 37: 10, 38: 10, 39: 10, 42: 11, 43: 12, 44: 13, 54: 14, 55: 15, 56: 16, 57: 17 };

/** phrase index -> which part of the abacus this line is about */
export const LINE_HIGHLIGHT: Record<number, "frame" | "rods" | "beam" | "top" | "bottom"> = { 9: "frame", 10: "frame", 11: "rods", 12: "rods", 13: "rods", 14: "beam", 15: "beam", 16: "beam", 17: "beam", 18: "top", 19: "bottom", 20: "top", 21: "top", 22: "bottom", 23: "bottom", 29: "bottom", 30: "top", 31: "top", 35: "bottom", 36: "top", 38: "bottom", 39: "top", 54: "bottom", 55: "top", 56: "bottom", 57: "top" };

/** phrase index -> number the beads while the narration counts them */
export const LINE_COUNT: Record<number, "upper" | "lower"> = { 21: "upper", 23: "lower" };
